### ISSUE TITLE
Reciprocal space demo is broken on python 3...

### ISSUE THREAD

**Issue by ericdill** [scikit-xray/scikit-xray-examples#26]
...for technical reasons that I do not understand. We are skipping the process_to_q test https://github.com/Nikea/scikit-xray/blob/master/skxray/tests/test_recip.py#L52 and we should probably sort out how to not skip that test

**Comment by tacaswell** [comment]
Because the c-api changed between pyhon2 and python3 and no one has gotten to exposing it in python3 yet.  @licode Has expressed interest in doing this.

We can also switch to using cython to do to the wrapping (I have a working example from one of the tutorials) which will take care of that detail for us.

I am +0.5 on doing it by hand and +1 on using cython.

**Comment by ericdill** [comment]
Ah ok. Thanks for the clear explanation.  I would imagine cython is the better route going forward, as it **should** mean that we wont have to worry about api breaks between python versions. Is that a reasonable assumption?

**Comment by tacaswell** [comment]
Yes, it would be cython's job to smooth that over, also to smooth over any changes to the numpy c-api.

**Comment by ericdill** [comment]
Closed by scikit-xray/scikit-xray#313
